## Daily

In [1]:
import pandas as pd
import numpy as np

In [2]:
d14 = (
    pd.read_csv(
        "rawdata/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv",
        dtype={"Id": str},
        parse_dates=["ActivityDate"]
    )
    .rename(columns={"ActivityDate": "ActivityDay"})
)
d13 = (
    pd.read_csv(
        "rawdata/Fitabase Data 3.12.16-4.11.16/dailyActivity_merged.csv",
        dtype={"Id": str},
        parse_dates=["ActivityDate"]
    )
    .rename(columns={"ActivityDate": "ActivityDay"})
)

d2 = (
    pd.read_csv(
        "rawdata/Fitabase Data 4.12.16-5.12.16/dailyCalories_merged.csv",
        dtype={"Id": str},
        parse_dates=["ActivityDay"]
    )
)

d3 = (
    pd.read_csv(
        "rawdata/Fitabase Data 4.12.16-5.12.16/dailyIntensities_merged.csv",
        dtype={"Id": str},
        parse_dates=["ActivityDay"]
    )
)

d4 = (
    pd.read_csv(
        "rawdata/Fitabase Data 4.12.16-5.12.16/dailySteps_merged.csv",
        dtype={"Id": str},
        parse_dates=["ActivityDay"]
    )
)


In [5]:
d14 = (
    pd.read_csv(
        "rawdata/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv",
        dtype={"Id": str},
        parse_dates=["ActivityDate"]
    )
)
d13 = (
    pd.read_csv(
        "rawdata/Fitabase Data 3.12.16-4.11.16/dailyActivity_merged.csv",
        dtype={"Id": str},
        parse_dates=["ActivityDate"]
    )
)

In [6]:
d1 = pd.concat([d13,d14])

In [9]:
import pyodbc

# Thông tin kết nối
conn_str = (
    r"Driver={ODBC Driver 17 for SQL Server};"
    r"Server=localhost\SQL_2022;"
    r"Database=fitbit;"
    r"Trusted_Connection=yes;"
)

# Kết nối
conn = pyodbc.connect(conn_str)
cursor = conn.cursor()

print("✅ Kết nối thành công đến database fitbit!")

✅ Kết nối thành công đến database fitbit!


In [12]:
from sqlalchemy import create_engine
import urllib
params = urllib.parse.quote_plus(conn_str)
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

d1.to_sql("daily_activity", con=engine, if_exists="replace", index=False)

print("✅ Đã ghi DataFrame d1 vào bảng daily_activity thành công!")

✅ Đã ghi DataFrame d1 vào bảng daily_activity thành công!


In [13]:
d4 = (
    pd.read_csv(
        "rawdata/Fitabase Data 4.12.16-5.12.16/dailySteps_merged.csv",
        dtype={"Id": str},
        parse_dates=["ActivityDay"]
    )
)

In [14]:
d4.to_sql("daily_steps", con=engine, if_exists="replace", index=False)

241

In [15]:
h14 = (
    pd.read_csv(
        "rawdata/Fitabase Data 4.12.16-5.12.16/hourlyCalories_merged.csv",
        dtype={"Id": str},
        parse_dates=["ActivityHour"]
    )
)
h24 = (
    pd.read_csv(
        "rawdata/Fitabase Data 4.12.16-5.12.16/hourlyIntensities_merged.csv",
        dtype={"Id": str},
        parse_dates=["ActivityHour"]
    )
)

h34 = (
    pd.read_csv(
        "rawdata/Fitabase Data 4.12.16-5.12.16/hourlySteps_merged.csv",
        dtype={"Id": str},
        parse_dates=["ActivityHour"]
    )
)

C:\Users\phong\AppData\Local\Temp\ipykernel_528\2684292791.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv(
C:\Users\phong\AppData\Local\Temp\ipykernel_528\2684292791.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv(
C:\Users\phong\AppData\Local\Temp\ipykernel_528\2684292791.py:17: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv(


In [16]:
h13 = (
    pd.read_csv(
        "rawdata/Fitabase Data 3.12.16-4.11.16/hourlyCalories_merged.csv",
        dtype={"Id": str},
        parse_dates=["ActivityHour"]
    )
)
h23 = (
    pd.read_csv(
        "rawdata/Fitabase Data 3.12.16-4.11.16/hourlyIntensities_merged.csv",
        dtype={"Id": str},
        parse_dates=["ActivityHour"]
    )
)

h33 = (
    pd.read_csv(
        "rawdata/Fitabase Data 3.12.16-4.11.16/hourlySteps_merged.csv",
        dtype={"Id": str},
        parse_dates=["ActivityHour"]
    )
)

C:\Users\phong\AppData\Local\Temp\ipykernel_528\2933609277.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv(
C:\Users\phong\AppData\Local\Temp\ipykernel_528\2933609277.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv(
C:\Users\phong\AppData\Local\Temp\ipykernel_528\2933609277.py:17: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv(


In [21]:
h1 = pd.concat([h13,h14])
h2 = pd.concat([h23,h24])
h3 = pd.concat([h33,h34])

In [22]:
hourlydf = h1\
.merge(h2, on = ['Id', 'ActivityHour'])\
.merge(h3, on = ['Id', 'ActivityHour'])

In [23]:
hourlydf.shape

(47233, 6)

In [24]:
hourlydf.to_sql("hourly_activity", con=engine, if_exists="replace", index=False)

118

In [25]:
sleepdaydf = (
    pd.read_csv(
        "rawdata/Fitabase Data 4.12.16-5.12.16/sleepDay_merged.csv",
        dtype={"Id": str},
        parse_dates=["SleepDay"]
    )
)

C:\Users\phong\AppData\Local\Temp\ipykernel_528\3432124716.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv(


In [26]:
sleepdaydf.to_sql("sleep_day", con=engine, if_exists="replace", index=False)

413

In [27]:
weightloginfo4df = (
    pd.read_csv(
        "rawdata/Fitabase Data 4.12.16-5.12.16/weightLogInfo_merged.csv",
        dtype={"Id": str},
        parse_dates=["Date"]
    )
)
weightloginfo3df = (
    pd.read_csv(
        "rawdata/Fitabase Data 3.12.16-4.11.16/weightLogInfo_merged.csv",
        dtype={"Id": str},
        parse_dates=["Date"]
    )
)

C:\Users\phong\AppData\Local\Temp\ipykernel_528\1550010163.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv(
C:\Users\phong\AppData\Local\Temp\ipykernel_528\1550010163.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv(


In [28]:
weightloginfo4df.columns == weightloginfo3df.columns

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [29]:
weightlogdf = pd.concat([weightloginfo3df, weightloginfo4df])

In [30]:
weightlogdf.to_sql("weight_log", con=engine, if_exists="replace", index=False)

100

In [34]:
import glob
import os
path4 = "rawdata/Fitabase Data 4.12.16-5.12.16/"
path3 = "rawdata/Fitabase Data 3.12.16-4.11.16/"
narrow_files_04 = glob.glob(os.path.join(path, "*Narrow_merged.csv"))
narrow_files_03 = glob.glob(os.path.join(path, "*Narrow_merged.csv"))

In [35]:
narrow_files_03,narrow_files_04

(['rawdata/Fitabase Data 4.12.16-5.12.16\\minuteCaloriesNarrow_merged.csv',
  'rawdata/Fitabase Data 4.12.16-5.12.16\\minuteIntensitiesNarrow_merged.csv',
  'rawdata/Fitabase Data 4.12.16-5.12.16\\minuteMETsNarrow_merged.csv',
  'rawdata/Fitabase Data 4.12.16-5.12.16\\minuteStepsNarrow_merged.csv'],
 ['rawdata/Fitabase Data 4.12.16-5.12.16\\minuteCaloriesNarrow_merged.csv',
  'rawdata/Fitabase Data 4.12.16-5.12.16\\minuteIntensitiesNarrow_merged.csv',
  'rawdata/Fitabase Data 4.12.16-5.12.16\\minuteMETsNarrow_merged.csv',
  'rawdata/Fitabase Data 4.12.16-5.12.16\\minuteStepsNarrow_merged.csv'])

In [36]:
merged_df_04 = None
for file in narrow_files_04:
    df = pd.read_csv(file, dtype={"Id": str}, parse_dates=["ActivityMinute"])
    if merged_df_04 is None:
        merged_df_04 = df
    else:
        merged_df_04 = merged_df_04.merge(df, on=['Id', 'ActivityMinute'], how='outer')

C:\Users\phong\AppData\Local\Temp\ipykernel_528\2574472580.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(file, dtype={"Id": str}, parse_dates=["ActivityMinute"])
C:\Users\phong\AppData\Local\Temp\ipykernel_528\2574472580.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(file, dtype={"Id": str}, parse_dates=["ActivityMinute"])
C:\Users\phong\AppData\Local\Temp\ipykernel_528\2574472580.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(file, dtype={"Id": str}, parse_dates=["ActivityMinute"])
C:\Users\phong\AppData\Lo

In [37]:
merged_df_03 = None
for file in narrow_files_03:
    df = pd.read_csv(file, dtype={"Id": str}, parse_dates=["ActivityMinute"])
    if merged_df_03 is None:
        merged_df_03 = df
    else:
        merged_df_03 = merged_df_03.merge(df, on=['Id', 'ActivityMinute'], how='outer')

C:\Users\phong\AppData\Local\Temp\ipykernel_528\2219959460.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(file, dtype={"Id": str}, parse_dates=["ActivityMinute"])
C:\Users\phong\AppData\Local\Temp\ipykernel_528\2219959460.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(file, dtype={"Id": str}, parse_dates=["ActivityMinute"])
C:\Users\phong\AppData\Local\Temp\ipykernel_528\2219959460.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(file, dtype={"Id": str}, parse_dates=["ActivityMinute"])
C:\Users\phong\AppData\Lo

In [38]:
merged_df_04.columns == merged_df_03.columns

array([ True,  True,  True,  True,  True,  True])

In [40]:
merged_df_03.shape

(1325580, 6)

In [41]:
merged_df = pd.concat([merged_df_03, merged_df_04])

In [42]:
merged_df.to_sql("minutely_narrow_activity", con=engine, if_exists="replace", index=False)

156

In [43]:
path = "rawdata/Fitabase Data 4.12.16-5.12.16/"
wide_files = glob.glob(os.path.join(path, "*Wide_merged.csv"))

for file in wide_files:
    table_name = os.path.basename(file).split('_')[0]
    df = pd.read_csv(file, dtype={"Id": str})
    df.to_sql(table_name, con=engine, if_exists="replace", index=False)
    print(table_name)

minuteCaloriesWide
minuteIntensitiesWide
minuteStepsWide


In [44]:
minutesleepdf_04 = (
    pd.read_csv(
        "rawdata/Fitabase Data 4.12.16-5.12.16/minuteSleep_merged.csv",
        dtype={"Id": str},
        parse_dates=["date"]
    )
)
minutesleepdf_03 = (
    pd.read_csv(
        "rawdata/Fitabase Data 3.12.16-4.11.16/minuteSleep_merged.csv",
        dtype={"Id": str},
        parse_dates=["date"]
    )
)

In [45]:
minutesleepdf_04.columns == minutesleepdf_03.columns

array([ True,  True,  True,  True])

In [46]:
minutesleepdf = pd.concat([minutesleepdf_03, minutesleepdf_04])

In [47]:
minutesleepdf.to_sql("sleep_minute", con=engine, if_exists="replace", index=False)

368

In [48]:
heartratedf_04 = (
    pd.read_csv(
        "rawdata/Fitabase Data 4.12.16-5.12.16/heartrate_seconds_merged.csv",
        dtype={"Id": str},
        parse_dates=["Time"]
    )
)
heartratedf_03 = (
    pd.read_csv(
        "rawdata/Fitabase Data 3.12.16-4.11.16/heartrate_seconds_merged.csv",
        dtype={"Id": str},
        parse_dates=["Time"]
    )
)

In [49]:
heartratedf_04.columns == heartratedf_03.columns

array([ True,  True,  True])

In [50]:
heartratedf = pd.concat([heartratedf_03, heartratedf_04])

In [51]:
heartratedf.to_sql("heartrate", con=engine, if_exists="replace", index=False)

44

In [ ]:
conn.close()